bot_name: phiduhok_bot
telegram_token: POPULATE_TOKEN_HERE
content_dir: memes
db_path: memes.db
allowed_add_ids:
  - TYPE
  - IDS
allowed_delete_ids:
  - TYPE
  - IDS
log_level: INFO
log_format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'